package org.stopbadware.dsp.json;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * Serialization wrapper for marshaling/unmarhsaling 
 * Autonomous System related data generated by the Resolver
 *
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class AutonomousSystem implements Response {

	private int asn;
	private String country;
	private String name;
	
	public AutonomousSystem() {
		setAsn(0);
		setCountry("");
		setName("");
	}

	public int getAsn() {
		return asn;
	}

	public void setAsn(int asn) {
		this.asn = asn;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Override
	public int hashCode() {
		return asn;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (obj instanceof AutonomousSystem) {
			return ((AutonomousSystem) obj).getAsn() == this.asn;
		} else {
			return false;
		}
	}
	
}
